services:
  server:
    image: prj-vm/prj-testimonial-server:latest
    container_name: prj-testimonial-server
    build: 
      context: ./server
      dockerfile: Dockerfile
      args:
        - MONGO_PWD
        - MONGO_USERNAME
        - MONGO_CLIENT_PROTOCOL
        - MONGO_SERVER_AND_PORT
        - PORT=${PORT-5050}
    ports:
      - "${PORT-5050}:${PORT-5050}" # Expose server on port 8080
    depends_on:
      - mongodb
    networks:
      - prj-testimonial-network
    restart: unless-stopped

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: prj-testimonial-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD}
    ports:
      - 27017:27017
    volumes:
      - prj_vm_mongodata:/data/db
    networks:
      - prj-testimonial-network
    restart: unless-stopped


volumes:
  prj_vm_mongodata:
    driver: local

networks:
  prj-testimonial-network:
    driver: bridge