gapi.loaded_0(function(_){var window=this;
_._F_toggles_initialize=function(a){(typeof globalThis!=="undefined"?globalThis:typeof self!=="undefined"?self:this)._F_toggles=a||[]};(0,_._F_toggles_initialize)([]);
var ia,ja,la,qa,Ea,Fa,La,Ma;_.fa=function(a){return function(){return _.ba[a].apply(this,arguments)}};_.ba=[];ia=typeof Object.create=="function"?Object.create:function(a){var b=function(){};b.prototype=a;return new b};ja=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
la=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("a");};_.pa=la(this);qa="Int8 Uint8 Uint8Clamped Int16 Uint16 Int32 Uint32 Float32 Float64".split(" ");_.pa.BigInt64Array&&(qa.push("BigInt64"),qa.push("BigUint64"));
var va=function(a,b){if(b)for(var c=0;c<qa.length;c++)ra(qa[c]+"Array.prototype."+a,b)},wa=function(a,b){b&&ra(a,b)},ra=function(a,b){var c=_.pa;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ja(c,a,{configurable:!0,writable:!0,value:b})},za;
if(typeof Object.setPrototypeOf=="function")za=Object.setPrototypeOf;else{var Aa;a:{var Ba={a:!0},Da={};try{Da.__proto__=Ba;Aa=Da.a;break a}catch(a){}Aa=!1}za=Aa?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}Ea=za;
_.u=function(a,b){a.prototype=ia(b.prototype);a.prototype.constructor=a;if(Ea)Ea(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.N=b.prototype};Fa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};
_.Ga=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:Fa(a)};throw Error("b`"+String(a));};La=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};Ma=typeof Object.assign=="function"?Object.assign:function(a,b){if(a==null)throw new TypeError("No nullish arg");a=Object(a);for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)La(d,e)&&(a[e]=d[e])}return a};
wa("Object.assign",function(a){return a||Ma});_.Pa=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};_.Qa=function(){this.CL=!1;this.El=null;this.Dh=void 0;this.Gc=1;this.zk=this.Nn=0;this.pJ=this.Yf=null};_.Qa.prototype.Zs=_.fa(0);_.Qa.prototype.zn=_.fa(1);_.Qa.prototype.Vr=_.fa(2);_.Qa.prototype.kt=_.fa(3);_.Qa.prototype.getNextAddressJsc=function(){return this.Gc};_.Qa.prototype.getYieldResultJsc=function(){return this.Dh};
_.Qa.prototype.return=function(a){this.Yf={return:a};this.Gc=this.zk};_.Qa.prototype["return"]=_.Qa.prototype.return;_.Qa.prototype.qja=function(a){this.Yf={Nf:a};this.Gc=this.zk};_.Qa.prototype.jumpThroughFinallyBlocks=_.Qa.prototype.qja;_.Qa.prototype.Be=function(a,b){this.Gc=b;return{value:a}};_.Qa.prototype.yield=_.Qa.prototype.Be;_.Qa.prototype.Voa=function(a,b){a=_.Ga(a);var c=a.next();_.Pa(c);if(c.done)this.Dh=c.value,this.Gc=b;else return this.El=a,this.Be(c.value,b)};
_.Qa.prototype.yieldAll=_.Qa.prototype.Voa;_.Qa.prototype.Nf=function(a){this.Gc=a};_.Qa.prototype.jumpTo=_.Qa.prototype.Nf;_.Qa.prototype.FL=function(){this.Gc=0};_.Qa.prototype.jumpToEnd=_.Qa.prototype.FL;_.Qa.prototype.jO=function(a,b){this.Nn=a;b!=void 0&&(this.zk=b)};_.Qa.prototype.setCatchFinallyBlocks=_.Qa.prototype.jO;_.Qa.prototype.fna=function(a){this.Nn=0;this.zk=a||0};_.Qa.prototype.setFinallyBlock=_.Qa.prototype.fna;_.Qa.prototype.J_=function(a,b){this.Gc=a;this.Nn=b||0};
_.Qa.prototype.leaveTryBlock=_.Qa.prototype.J_;_.Qa.prototype.XI=function(a){this.Nn=a||0;a=this.Yf.HV;this.Yf=null;return a};_.Qa.prototype.enterCatchBlock=_.Qa.prototype.XI;_.Qa.prototype.CV=function(a,b,c){c?this.pJ[c]=this.Yf:this.pJ=[this.Yf];this.Nn=a||0;this.zk=b||0};_.Qa.prototype.enterFinallyBlock=_.Qa.prototype.CV;
_.Qa.prototype.I_=function(a,b){b=this.pJ.splice(b||0)[0];(b=this.Yf=this.Yf||b)?b.JZ?this.Gc=this.Nn||this.zk:b.Nf!=void 0&&this.zk<b.Nf?(this.Gc=b.Nf,this.Yf=null):this.Gc=this.zk:this.Gc=a};_.Qa.prototype.leaveFinallyBlock=_.Qa.prototype.I_;_.Qa.prototype.Zea=function(a){return new Sa(a)};_.Qa.prototype.forIn=_.Qa.prototype.Zea;var Sa=function(a){this.zw=a;this.PC=[];for(var b in a)this.PC.push(b);this.PC.reverse()};
Sa.prototype.oga=function(){for(;this.PC.length>0;){var a=this.PC.pop();if(a in this.zw)return a}return null};Sa.prototype.getNext=Sa.prototype.oga;wa("globalThis",function(a){return a||_.pa});wa("Reflect.setPrototypeOf",function(a){return a?a:Ea?function(b,c){try{return Ea(b,c),!0}catch(d){return!1}}:null});
wa("Symbol",function(a){if(a)return a;var b=function(f,h){this.R7=f;ja(this,"description",{configurable:!0,writable:!0,value:h})};b.prototype.toString=function(){return this.R7};var c="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e});
wa("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");ja(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return Va(Fa(this))}});return a});var Va=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
wa("Promise",function(a){function b(){this.Af=null}function c(h){return h instanceof e?h:new e(function(k){k(h)})}if(a)return a;b.prototype.FS=function(h){if(this.Af==null){this.Af=[];var k=this;this.GS(function(){k.Iea()})}this.Af.push(h)};var d=_.pa.setTimeout;b.prototype.GS=function(h){d(h,0)};b.prototype.Iea=function(){for(;this.Af&&this.Af.length;){var h=this.Af;this.Af=[];for(var k=0;k<h.length;++k){var l=h[k];h[k]=null;try{l()}catch(m){this.vq(m)}}}this.Af=null};b.prototype.vq=function(h){this.GS(function(){throw h;
})};var e=function(h){this.Fa=0;this.uf=void 0;this.cs=[];this.XZ=!1;var k=this.AI();try{h(k.resolve,k.reject)}catch(l){k.reject(l)}};e.prototype.AI=function(){function h(m){return function(n){l||(l=!0,m.call(k,n))}}var k=this,l=!1;return{resolve:h(this.Vla),reject:h(this.wN)}};e.prototype.Vla=function(h){if(h===this)this.wN(new TypeError("A Promise cannot resolve to itself"));else if(h instanceof e)this.Dna(h);else{a:switch(typeof h){case "object":var k=h!=null;break a;case "function":k=!0;break a;
default:k=!1}k?this.Ula(h):this.JW(h)}};e.prototype.Ula=function(h){var k=void 0;try{k=h.then}catch(l){this.wN(l);return}typeof k=="function"?this.Ena(k,h):this.JW(h)};e.prototype.wN=function(h){this.p5(2,h)};e.prototype.JW=function(h){this.p5(1,h)};e.prototype.p5=function(h,k){if(this.Fa!=0)throw Error("c`"+h+"`"+k+"`"+this.Fa);this.Fa=h;this.uf=k;this.Fa===2&&this.kma();this.Jea()};e.prototype.kma=function(){var h=this;d(function(){if(h.ika()){var k=_.pa.console;typeof k!=="undefined"&&k.error(h.uf)}},
1)};e.prototype.ika=function(){if(this.XZ)return!1;var h=_.pa.CustomEvent,k=_.pa.Event,l=_.pa.dispatchEvent;if(typeof l==="undefined")return!0;typeof h==="function"?h=new h("unhandledrejection",{cancelable:!0}):typeof k==="function"?h=new k("unhandledrejection",{cancelable:!0}):(h=_.pa.document.createEvent("CustomEvent"),h.initCustomEvent("unhandledrejection",!1,!0,h));h.promise=this;h.reason=this.uf;return l(h)};e.prototype.Jea=function(){if(this.cs!=null){for(var h=0;h<this.cs.length;++h)f.FS(this.cs[h]);
this.cs=null}};var f=new b;e.prototype.Dna=function(h){var k=this.AI();h.iz(k.resolve,k.reject)};e.prototype.Ena=function(h,k){var l=this.AI();try{h.call(k,l.resolve,l.reject)}catch(m){l.reject(m)}};e.prototype.then=function(h,k){function l(q,r){return typeof q=="function"?function(v){try{m(q(v))}catch(t){n(t)}}:r}var m,n,p=new e(function(q,r){m=q;n=r});this.iz(l(h,m),l(k,n));return p};e.prototype.catch=function(h){return this.then(void 0,h)};e.prototype.iz=function(h,k){function l(){switch(m.Fa){case 1:h(m.uf);
break;case 2:k(m.uf);break;default:throw Error("d`"+m.Fa);}}var m=this;this.cs==null?f.FS(l):this.cs.push(l);this.XZ=!0};e.resolve=c;e.reject=function(h){return new e(function(k,l){l(h)})};e.race=function(h){return new e(function(k,l){for(var m=_.Ga(h),n=m.next();!n.done;n=m.next())c(n.value).iz(k,l)})};e.all=function(h){var k=_.Ga(h),l=k.next();return l.done?c([]):new e(function(m,n){function p(v){return function(t){q[v]=t;r--;r==0&&m(q)}}var q=[],r=0;do q.push(void 0),r++,c(l.value).iz(p(q.length-
1),n),l=k.next();while(!l.done)})};return e});var Za=function(a,b,c){if(a==null)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
wa("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=Za(this,b,"startsWith"),e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var h=0;h<f&&c<e;)if(d[c++]!=b[h++])return!1;return h>=f}});wa("Object.setPrototypeOf",function(a){return a||Ea});wa("Symbol.dispose",function(a){return a?a:Symbol("Symbol.dispose")});
wa("WeakMap",function(a){function b(){}function c(l){var m=typeof l;return m==="object"&&l!==null||m==="function"}function d(l){if(!La(l,f)){var m=new b;ja(l,f,{value:m})}}function e(l){var m=Object[l];m&&(Object[l]=function(n){if(n instanceof b)return n;Object.isExtensible(n)&&d(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),m=Object.seal({}),n=new a([[l,2],[m,3]]);if(n.get(l)!=2||n.get(m)!=3)return!1;n.delete(l);n.set(m,4);return!n.has(l)&&n.get(m)==4}catch(p){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var h=0,k=function(l){this.Ha=(h+=Math.random()+1).toString();if(l){l=_.Ga(l);for(var m;!(m=l.next()).done;)m=m.value,this.set(m[0],m[1])}};k.prototype.set=function(l,m){if(!c(l))throw Error("e");d(l);if(!La(l,f))throw Error("f`"+l);l[f][this.Ha]=m;return this};k.prototype.get=function(l){return c(l)&&La(l,f)?l[f][this.Ha]:void 0};k.prototype.has=function(l){return c(l)&&La(l,f)&&La(l[f],this.Ha)};k.prototype.delete=
function(l){return c(l)&&La(l,f)&&La(l[f],this.Ha)?delete l[f][this.Ha]:!1};return k});
wa("Map",function(a){if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var k=Object.seal({x:4}),l=new a(_.Ga([[k,"s"]]));if(l.get(k)!="s"||l.size!=1||l.get({x:4})||l.set({x:4},"t")!=l||l.size!=2)return!1;var m=l.entries(),n=m.next();if(n.done||n.value[0]!=k||n.value[1]!="s")return!1;n=m.next();return n.done||n.value[0].x!=4||n.value[1]!="t"||!m.next().done?!1:!0}catch(p){return!1}}())return a;var b=new WeakMap,c=function(k){this[0]={};this[1]=
f();this.size=0;if(k){k=_.Ga(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}};c.prototype.set=function(k,l){k=k===0?0:k;var m=d(this,k);m.list||(m.list=this[0][m.id]=[]);m.entry?m.entry.value=l:(m.entry={next:this[1],Sk:this[1].Sk,head:this[1],key:k,value:l},m.list.push(m.entry),this[1].Sk.next=m.entry,this[1].Sk=m.entry,this.size++);return this};c.prototype.delete=function(k){k=d(this,k);return k.entry&&k.list?(k.list.splice(k.index,1),k.list.length||delete this[0][k.id],k.entry.Sk.next=
k.entry.next,k.entry.next.Sk=k.entry.Sk,k.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this[0]={};this[1]=this[1].Sk=f();this.size=0};c.prototype.has=function(k){return!!d(this,k).entry};c.prototype.get=function(k){return(k=d(this,k).entry)&&k.value};c.prototype.entries=function(){return e(this,function(k){return[k.key,k.value]})};c.prototype.keys=function(){return e(this,function(k){return k.key})};c.prototype.values=function(){return e(this,function(k){return k.value})};c.prototype.forEach=
function(k,l){for(var m=this.entries(),n;!(n=m.next()).done;)n=n.value,k.call(l,n[1],n[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(k,l){var m=l&&typeof l;m=="object"||m=="function"?b.has(l)?m=b.get(l):(m=""+ ++h,b.set(l,m)):m="p_"+l;var n=k[0][m];if(n&&La(k[0],m))for(k=0;k<n.length;k++){var p=n[k];if(l!==l&&p.key!==p.key||l===p.key)return{id:m,list:n,index:k,entry:p}}return{id:m,list:n,index:-1,entry:void 0}},e=function(k,l){var m=k[1];return Va(function(){if(m){for(;m.head!=
k[1];)m=m.Sk;for(;m.next!=m.head;)return m=m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})},f=function(){var k={};return k.Sk=k.next=k.head=k},h=0;return c});
wa("Set",function(a){if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var c=Object.seal({x:4}),d=new a(_.Ga([c]));if(!d.has(c)||d.size!=1||d.add(c)!=d||d.size!=1||d.add({x:4})!=d||d.size!=2)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=c||f.value[1]!=c)return!1;f=e.next();return f.done||f.value[0]==c||f.value[0].x!=4||f.value[1]!=f.value[0]?!1:e.next().done}catch(h){return!1}}())return a;var b=function(c){this.Ta=new Map;if(c){c=
_.Ga(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.Ta.size};b.prototype.add=function(c){c=c===0?0:c;this.Ta.set(c,c);this.size=this.Ta.size;return this};b.prototype.delete=function(c){c=this.Ta.delete(c);this.size=this.Ta.size;return c};b.prototype.clear=function(){this.Ta.clear();this.size=0};b.prototype.has=function(c){return this.Ta.has(c)};b.prototype.entries=function(){return this.Ta.entries()};b.prototype.values=function(){return this.Ta.values()};b.prototype.keys=b.prototype.values;
b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.Ta.forEach(function(f){return c.call(d,f,f,e)})};return b});var ab=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};wa("Array.prototype.entries",function(a){return a?a:function(){return ab(this,function(b,c){return[b,c]})}});
wa("Array.prototype.keys",function(a){return a?a:function(){return ab(this,function(b){return b})}});wa("String.prototype.codePointAt",function(a){return a?a:function(b){var c=Za(this,null,"codePointAt"),d=c.length;b=Number(b)||0;if(b>=0&&b<d){b|=0;var e=c.charCodeAt(b);if(e<55296||e>56319||b+1===d)return e;b=c.charCodeAt(b+1);return b<56320||b>57343?e:(e-55296)*1024+b+9216}}});
wa("String.fromCodePoint",function(a){return a?a:function(b){for(var c="",d=0;d<arguments.length;d++){var e=Number(arguments[d]);if(e<0||e>1114111||e!==Math.floor(e))throw new RangeError("invalid_code_point "+e);e<=65535?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(e>>>10&1023|55296),c+=String.fromCharCode(e&1023|56320))}return c}});wa("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)La(b,d)&&c.push([d,b[d]]);return c}});
wa("String.prototype.endsWith",function(a){return a?a:function(b,c){var d=Za(this,b,"endsWith");c===void 0&&(c=d.length);c=Math.max(0,Math.min(c|0,d.length));for(var e=b.length;e>0&&c>0;)if(d[--c]!=b[--e])return!1;return e<=0}});wa("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});
wa("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var h=d[f];if(b.call(c,h,f,d)){b=h;break a}}b=void 0}return b}});wa("Array.prototype.values",function(a){return a?a:function(){return ab(this,function(b,c){return c})}});
wa("Promise.prototype.finally",function(a){return a?a:function(b){return this.then(function(c){return Promise.resolve(b()).then(function(){return c})},function(c){return Promise.resolve(b()).then(function(){throw c;})})}});wa("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});
wa("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});wa("String.prototype.includes",function(a){return a?a:function(b,c){return Za(this,b,"includes").indexOf(b,c||0)!==-1}});
wa("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(k){return k};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var h=0;!(f=b.next()).done;)e.push(c.call(d,f.value,h++))}else for(f=b.length,h=0;h<f;h++)e.push(c.call(d,b[h],h));return e}});wa("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)La(b,d)&&c.push(b[d]);return c}});
wa("Set.prototype.intersection",function(a){return a?a:function(b){if(!(this instanceof Set))throw new TypeError("Method must be called on an instance of Set.");if(typeof b!=="object"||b===null||typeof b.size!=="number"||b.size<0||typeof b.keys!=="function"||typeof b.has!=="function")throw new TypeError("Argument must be set-like");var c=new Set;if(this.size<=b.size)b={P5:this.keys(),w_:b};else{b=b.keys();if(typeof b!=="object"||b===null||typeof b.next!=="function")throw new TypeError("Invalid iterator.");
b={P5:b,w_:this}}var d=b;b=d.P5;d=d.w_;for(var e=b.next();!e.done;)d.has(e.value)&&c.add(e.value),e=b.next();return c}});wa("Array.prototype.flat",function(a){return a?a:function(b){b=b===void 0?1:b;var c=[];Array.prototype.forEach.call(this,function(d){Array.isArray(d)&&b>0?(d=Array.prototype.flat.call(d,b-1),c.push.apply(c,d)):c.push(d)});return c}});wa("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});wa("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});
wa("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});wa("Number.isSafeInteger",function(a){return a?a:function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}});wa("Array.prototype.flatMap",function(a){return a?a:function(b,c){var d=[];Array.prototype.forEach.call(this,function(e,f){e=b.call(c,e,f,this);Array.isArray(e)?d.push.apply(d,e):d.push(e)});return d}});
wa("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||b===Infinity||b===-Infinity||b===0)return b;var c=Math.floor(Math.abs(b));return b<0?-c:c}});wa("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});
wa("WeakSet",function(a){if(function(){if(!a||!Object.seal)return!1;try{var c=Object.seal({}),d=Object.seal({}),e=new a([c]);if(!e.has(c)||e.has(d))return!1;e.delete(c);e.add(d);return!e.has(c)&&e.has(d)}catch(f){return!1}}())return a;var b=function(c){this.Ta=new WeakMap;if(c){c=_.Ga(c);for(var d;!(d=c.next()).done;)this.add(d.value)}};b.prototype.add=function(c){this.Ta.set(c,!0);return this};b.prototype.has=function(c){return this.Ta.has(c)};b.prototype.delete=function(c){return this.Ta.delete(c)};
return b});wa("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});var cb=function(a){a=Math.trunc(a)||0;a<0&&(a+=this.length);if(!(a<0||a>=this.length))return this[a]};
wa("Array.prototype.at",function(a){return a?a:cb});va("at",function(a){return a?a:cb});wa("String.prototype.at",function(a){return a?a:cb});wa("Math.imul",function(a){return a?a:function(b,c){b=Number(b);c=Number(c);var d=b&65535,e=c&65535;return d*e+((b>>>16&65535)*e+d*(c>>>16&65535)<<16>>>0)|0}});_.eb={};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.fb=_.fb||{};_.hb=this||self;_.ib=_.hb._F_toggles||[];_.jb="closure_uid_"+(Math.random()*1E9>>>0);_.lb=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}};_.w=function(a,b){a=a.split(".");for(var c=_.hb,d;a.length&&(d=a.shift());)a.length||b===void 0?c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}:c[d]=b};_.mb=window.osapi=window.osapi||{};
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},csi:{rate:.01},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/:session_prefix:_/widget/render/badge?usegapi=1"},":socialhost:":"https://apis.google.com",":im_socialhost:":"https://plus.googleapis.com",domains_suggest:{url:"https://domains.google.com/suggest/flow"},card:{params:{s:"#",userid:"&"},
url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",":gplus_url:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton?usegapi=1"},plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true&usegapi=1"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle?usegapi=1"},plus_followers:{url:":socialhost:/_/im/_/widget/render/plus/followers?usegapi=1"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator?usegapi=1"},
appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},page:{url:":socialhost:/:session_prefix:_/widget/render/page?usegapi=1"},person:{url:":socialhost:/:session_prefix:_/widget/render/person?usegapi=1"},community:{url:":ctx_socialhost:/:session_prefix::im_prefix:_/widget/render/community?usegapi=1"},follow:{url:":socialhost:/:session_prefix:_/widget/render/follow?usegapi=1"},commentcount:{url:":socialhost:/:session_prefix:_/widget/render/commentcount?usegapi=1"},comments:{url:":socialhost:/:session_prefix:_/widget/render/comments?usegapi=1"},
blogger:{url:":socialhost:/:session_prefix:_/widget/render/blogger?usegapi=1"},youtube:{url:":socialhost:/:session_prefix:_/widget/render/youtube?usegapi=1"},reportabuse:{url:":socialhost:/:session_prefix:_/widget/render/reportabuse?usegapi=1"},additnow:{url:":socialhost:/additnow/additnow.html"},appfinder:{url:"https://workspace.google.com/:session_prefix:marketplace/appfinder?usegapi=1"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{rpc:"/rpc",root:"https://content.googleapis.com",
"root-1p":"https://clients6.google.com",useGapiForXd3:!0,xd3:"/static/proxy.html",auth:{useInterimAuth:!1}},report:{apis:["iframes\\..*","gadgets\\..*","gapi\\.appcirclepicker\\..*","gapi\\.client\\..*"],rate:1E-4},client:{perApiBatch:!0},gen204logger:{interval:3E4,rate:.001,batch:!1}});
var pb;_.ob=function(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,_.ob);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));b!==void 0&&(this.cause=b);this.q3=!0};pb=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");_.ob.call(this,c+a[d])};
_.sb=function(a,b){function c(){}c.prototype=b.prototype;a.N=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(d,e,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}};_.sb(_.ob,Error);_.ob.prototype.name="CustomError";_.sb(pb,_.ob);pb.prototype.name="AssertionError";
var Ab,Bb,Db;_.tb=function(a,b){return _.ba[a]=b};_.ub=function(a,b){throw Error(b===void 0?"unexpected value "+a+"!":b);};_.wb=function(a,b){return(0,_.vb)(a,b)>=0};_.xb=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};_.yb=function(a){var b=typeof a;return b=="object"&&a!=null||b=="function"};_.zb=function(a,b){a=a.split(".");b=b||_.hb;for(var c=0;c<a.length;c++)if(b=b[a[c]],b==null)return null;return b};
Ab=function(a,b){var c=_.zb("WIZ_global_data.oxN3nb");a=c&&c[a];return a!=null?a:b};Bb=function(a,b,c){return a.call.apply(a.bind,arguments)};Db=function(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}};
_.Eb=function(a,b,c){_.Eb=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?Bb:Db;return _.Eb.apply(null,arguments)};_.vb=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.Fb=Array.prototype.lastIndexOf?function(a,b){return Array.prototype.lastIndexOf.call(a,b,a.length-1)}:function(a,b){var c=a.length-1;c<0&&(c=Math.max(0,a.length+c));if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.lastIndexOf(b,c);for(;c>=0;c--)if(c in a&&a[c]===b)return c;return-1};_.Ib=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=typeof a==="string"?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.Jb=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f=typeof a==="string"?a.split(""):a,h=0;h<c;h++)if(h in f){var k=f[h];b.call(void 0,k,h,a)&&(d[e++]=k)}return d};_.Mb=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=typeof a==="string"?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};
_.Nb=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=typeof a==="string"?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.Ob=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=typeof a==="string"?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};var Pb=!!(_.ib[0]>>20&1),Rb=!!(_.ib[0]>>15&1),Sb=!!(_.ib[0]>>22&1),Tb=!!(_.ib[0]&64),Ub=!!(_.ib[0]>>23&1),Vb=!!(_.ib[0]&1024);_.Wb=Pb?Sb:Ab(610401301,!1);_.Yb=Pb?Tb:Ab(1331761403,!1);_.Zb=Pb?Ub:Ab(651175828,!1);_.$b=Pb?Rb||!Vb:Ab(748402147,!0);_.ac=function(a){_.ac[" "](a);return a};_.ac[" "]=function(){};
/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var ec,hc,vc,Kc,Sc,ed,nd;_.bc=function(a){var b=a.length;if(b>0){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};_.cc=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};ec=function(){var a=null;if(!dc)return a;try{var b=function(c){return c};a=dc.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(c){}return a};hc=function(){fc===void 0&&(fc=ec());return fc};_.jc=function(a){var b=hc();a=b?b.createHTML(a):a;return new _.ic(a)};
_.kc=function(a){if(a instanceof _.ic)return a.C2;throw Error("j");};_.mc=function(a){return new _.lc(a)};_.oc=function(a){var b=hc();a=b?b.createScriptURL(a):a;return new _.nc(a)};_.pc=function(a){if(a instanceof _.nc)return a.D2;throw Error("j");};_.rc=function(a){return a instanceof _.qc};_.sc=function(a){if(_.rc(a))return a.G2;throw Error("j");};vc=function(a){return new _.uc(function(b){return b.substr(0,a.length+1).toLowerCase()===a+":"})};_.xc=function(a){if(wc.test(a))return a};
_.yc=function(a){return a instanceof _.qc?_.sc(a):_.xc(a)};_.Bc=function(a,b){if(a instanceof _.ic)return a;a=String(a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;");if(b==null?0:b.vza)a=a.replace(/(^|[\r\n\t ]) /g,"$1&#160;");if(b==null?0:b.jla)a=a.replace(/(\r\n|\n|\r)/g,"<br>");if(b==null?0:b.wza)a=a.replace(/(\t+)/g,'<span style="white-space:pre">$1</span>');return _.jc(a)};
_.Dc=function(a){var b=_.Cc.apply(1,arguments);if(b.length===0)return _.oc(a[0]);for(var c=a[0],d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return _.oc(c)};_.Ec=function(a,b){this.width=a;this.height=b};_.Gc=function(a,b){return a.lastIndexOf(b,0)==0};_.Hc=function(a){return/^[\s\xa0]*$/.test(a)};_.Ic=function(a,b){return a.indexOf(b)!=-1};
_.Lc=function(a,b){var c=0;a=(0,_.Jc)(String(a)).split(".");b=(0,_.Jc)(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;c==0&&e<d;e++){var f=a[e]||"",h=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(f[0].length==0&&h[0].length==0)break;c=Kc(f[1].length==0?0:parseInt(f[1],10),h[1].length==0?0:parseInt(h[1],10))||Kc(f[2].length==0,h[2].length==0)||Kc(f[2],h[2]);f=f[3];h=h[3]}while(c==0)}return c};
Kc=function(a,b){return a<b?-1:a>b?1:0};_.Mc=function(a,b){b=_.yc(b);b!==void 0&&(a.href=b)};_.Nc=function(a,b,c,d){b=_.yc(b);return b!==void 0?a.open(b,c,d):null};_.Oc=function(a,b){b=b===void 0?document:b;var c,d;b=(d=(c=b).querySelector)==null?void 0:d.call(c,a+"[nonce]");return b==null?"":b.nonce||b.getAttribute("nonce")||""};_.Pc=function(a,b){if(a.nodeType===1&&/^(script|style)$/i.test(a.tagName))throw Error("j");a.innerHTML=_.kc(b)};
_.Qc=function(){var a=_.hb.navigator;return a&&(a=a.userAgent)?a:""};Sc=function(a){if(!_.Wb||!_.Rc)return!1;for(var b=0;b<_.Rc.brands.length;b++){var c=_.Rc.brands[b].brand;if(c&&_.Ic(c,a))return!0}return!1};_.Tc=function(a){return _.Ic(_.Qc(),a)};_.Uc=function(a){for(var b=RegExp("([A-Z][\\w ]+)/([^\\s]+)\\s*(?:\\((.*?)\\))?","g"),c=[],d;d=b.exec(a);)c.push([d[1],d[2],d[3]||void 0]);return c};_.Vc=function(){return _.Wb?!!_.Rc&&_.Rc.brands.length>0:!1};_.Wc=function(){return _.Vc()?!1:_.Tc("Opera")};
_.Xc=function(){return _.Vc()?!1:_.Tc("Trident")||_.Tc("MSIE")};_.Yc=function(){return _.Vc()?!1:_.Tc("Edge")};_.Zc=function(){return _.Vc()?Sc("Microsoft Edge"):_.Tc("Edg/")};_.$c=function(){return _.Vc()?Sc("Opera"):_.Tc("OPR")};_.ad=function(){return _.Tc("Firefox")||_.Tc("FxiOS")};_.bd=function(){return _.Vc()?Sc("Chromium"):(_.Tc("Chrome")||_.Tc("CriOS"))&&!_.Yc()||_.Tc("Silk")};
_.cd=function(a){var b={};a.forEach(function(c){b[c[0]]=c[1]});return function(c){return b[c.find(function(d){return d in b})]||""}};_.dd=function(a){var b=/rv: *([\d\.]*)/.exec(a);if(b&&b[1])return b[1];b="";var c=/MSIE +([\d\.]+)/.exec(a);if(c&&c[1])if(a=/Trident\/(\d.\d)/.exec(a),c[1]=="7.0")if(a&&a[1])switch(a[1]){case "4.0":b="8.0";break;case "5.0":b="9.0";break;case "6.0":b="10.0";break;case "7.0":b="11.0"}else b="7.0";else b=c[1];return b};
ed=function(){return _.Wb?!!_.Rc&&!!_.Rc.platform:!1};_.fd=function(){return ed()?_.Rc.platform==="Android":_.Tc("Android")};_.gd=function(){return _.Tc("iPhone")&&!_.Tc("iPod")&&!_.Tc("iPad")};_.hd=function(){return _.gd()||_.Tc("iPad")||_.Tc("iPod")};_.id=function(){return ed()?_.Rc.platform==="macOS":_.Tc("Macintosh")};_.jd=function(){return ed()?_.Rc.platform==="Windows":_.Tc("Windows")};_.kd=function(){return ed()?_.Rc.platform==="Chrome OS":_.Tc("CrOS")};
_.Qa.prototype.Zs=_.tb(0,function(){if(this.CL)throw new TypeError("Generator is already running");this.CL=!0});_.ld=function(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a};_.md=function(a){return _.ld(a,a)};_.Cc=function(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};_.od=function(a){var b=typeof a;return b!="object"?b:a?Array.isArray(a)?"array":b:"null"};
_.pd=function(a){var b=_.od(a);return b=="array"||b=="object"&&typeof a.length=="number"};_.rd=function(){return Date.now()};var sd=globalThis.trustedTypes,dc=sd,fc;_.ic=function(a){this.C2=a};_.ic.prototype.toString=function(){return this.C2+""};_.td=function(){return new _.ic(sd?sd.emptyHTML:"")}();_.lc=function(a){this.E2=a};_.lc.prototype.toString=function(){return this.E2};_.nc=function(a){this.D2=a};_.nc.prototype.toString=function(){return this.D2+""};_.qc=function(a){this.G2=a};_.qc.prototype.toString=function(){return this.G2};_.ud=new _.qc("about:invalid#zClosurez");var wc;_.uc=function(a){this.Zc=a};_.vd=[vc("data"),vc("http"),vc("https"),vc("mailto"),vc("ftp"),new _.uc(function(a){return/^[^:]*([/?#]|$)/.test(a)})];_.wd=function(){return typeof URL==="function"}();wc=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;_.xd=function(a,b){return a==b?!0:a&&b?a.width==b.width&&a.height==b.height:!1};_.g=_.Ec.prototype;_.g.clone=function(){return new _.Ec(this.width,this.height)};_.g.area=function(){return this.width*this.height};_.g.aspectRatio=function(){return this.width/this.height};_.g.isEmpty=function(){return!this.area()};_.g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
_.g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};_.g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};_.g.scale=function(a,b){this.width*=a;this.height*=typeof b==="number"?b:a;return this};_.Jc=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};_.yd=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};_.Ad=Math.random()*2147483648|0;var Bd;Bd=_.hb.navigator;_.Rc=Bd?Bd.userAgentData||null:null;var Rd,Sd,Yd;_.Cd=_.Wc();_.Dd=_.Xc();_.Ed=_.Tc("Edge");_.Fd=_.Tc("Gecko")&&!(_.Ic(_.Qc().toLowerCase(),"webkit")&&!_.Tc("Edge"))&&!(_.Tc("Trident")||_.Tc("MSIE"))&&!_.Tc("Edge");_.Gd=_.Ic(_.Qc().toLowerCase(),"webkit")&&!_.Tc("Edge");_.Hd=_.Gd&&_.Tc("Mobile");_.Id=_.id();_.Jd=_.jd();_.Kd=(ed()?_.Rc.platform==="Linux":_.Tc("Linux"))||_.kd();_.Ld=_.fd();_.Md=_.gd();_.Nd=_.Tc("iPad");_.Pd=_.Tc("iPod");_.Qd=_.hd();Rd=function(){var a=_.hb.document;return a?a.documentMode:void 0};
a:{var Td="",Ud=function(){var a=_.Qc();if(_.Fd)return/rv:([^\);]+)(\)|;)/.exec(a);if(_.Ed)return/Edge\/([\d\.]+)/.exec(a);if(_.Dd)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.Gd)return/WebKit\/(\S+)/.exec(a);if(_.Cd)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Ud&&(Td=Ud?Ud[1]:"");if(_.Dd){var Wd=Rd();if(Wd!=null&&Wd>parseFloat(Td)){Sd=String(Wd);break a}}Sd=Td}_.Xd=Sd;if(_.hb.document&&_.Dd){var Zd=Rd();Yd=Zd?Zd:parseInt(_.Xd,10)||void 0}else Yd=void 0;_.$d=Yd;var fe,oe,ne;_.ce=function(a){return a?new _.ae(_.be(a)):nd||(nd=new _.ae)};_.de=function(a,b){return typeof b==="string"?a.getElementById(b):b};_.ee=function(a,b,c,d){a=d||a;return(b=b&&b!="*"?String(b).toUpperCase():"")||c?a.querySelectorAll(b+(c?"."+c:"")):a.getElementsByTagName("*")};
_.ie=function(a,b){_.cc(b,function(c,d){d=="style"?a.style.cssText=c:d=="class"?a.className=c:d=="for"?a.htmlFor=c:fe.hasOwnProperty(d)?a.setAttribute(fe[d],c):_.Gc(d,"aria-")||_.Gc(d,"data-")?a.setAttribute(d,c):a[d]=c})};fe={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};_.ke=function(a){return _.je(a||window)};
_.je=function(a){a=a.document;a=_.le(a)?a.documentElement:a.body;return new _.Ec(a.clientWidth,a.clientHeight)};_.me=function(a){return a?a.defaultView:window};_.pe=function(a,b){var c=b[1],d=ne(a,String(b[0]));c&&(typeof c==="string"?d.className=c:Array.isArray(c)?d.className=c.join(" "):_.ie(d,c));b.length>2&&oe(a,d,b,2);return d};
oe=function(a,b,c,d){function e(k){k&&b.appendChild(typeof k==="string"?a.createTextNode(k):k)}for(;d<c.length;d++){var f=c[d];if(!_.pd(f)||_.yb(f)&&f.nodeType>0)e(f);else{a:{if(f&&typeof f.length=="number"){if(_.yb(f)){var h=typeof f.item=="function"||typeof f.item=="string";break a}if(typeof f==="function"){h=typeof f.item=="function";break a}}h=!1}_.Ib(h?_.bc(f):f,e)}}};_.qe=function(a){return ne(document,a)};
ne=function(a,b){b=String(b);a.contentType==="application/xhtml+xml"&&(b=b.toLowerCase());return a.createElement(b)};_.le=function(a){return a.compatMode=="CSS1Compat"};_.re=function(a){if(a.nodeType!=1)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
_.se=function(a,b){oe(_.be(a),a,arguments,1)};_.te=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.ue=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};_.ve=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};_.xe=function(a){return a.children!=void 0?a.children:Array.prototype.filter.call(a.childNodes,function(b){return b.nodeType==1})};_.ye=function(a){return _.yb(a)&&a.nodeType==1};
_.ze=function(a,b){if(!a||!b)return!1;if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};_.be=function(a){return a.nodeType==9?a:a.ownerDocument||a.document};
_.Ae=function(a,b){if("textContent"in a)a.textContent=b;else if(a.nodeType==3)a.data=String(b);else if(a.firstChild&&a.firstChild.nodeType==3){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else _.te(a),a.appendChild(_.be(a).createTextNode(String(b)))};_.ae=function(a){this.Xb=a||_.hb.document||document};_.g=_.ae.prototype;_.g.Ia=_.ce;_.g.yO=_.fa(4);_.g.Ab=function(){return this.Xb};_.g.U=_.fa(5);_.g.getElementsByTagName=function(a,b){return(b||this.Xb).getElementsByTagName(String(a))};
_.g.wK=_.fa(6);_.g.Ca=function(a,b,c){return _.pe(this.Xb,arguments)};_.g.createElement=function(a){return ne(this.Xb,a)};_.g.createTextNode=function(a){return this.Xb.createTextNode(String(a))};_.g.getWindow=function(){return this.Xb.defaultView};_.g.appendChild=function(a,b){a.appendChild(b)};_.g.append=_.se;_.g.canHaveChildren=_.re;_.g.we=_.te;_.g.qZ=_.ue;_.g.removeNode=_.ve;_.g.EJ=_.xe;_.g.isElement=_.ye;_.g.contains=_.ze;_.g.aK=_.be;_.g.Cj=_.fa(7);
/*
 gapi.loader.OBJECT_CREATE_TEST_OVERRIDE &&*/
_.Be=function(a){return a===null?"null":a===void 0?"undefined":a};_.Ce=window;_.De=document;_.Ee=_.Ce.location;_.Fe=/\[native code\]/;_.Ge=function(a,b,c){return a[b]=a[b]||c};_.He=function(){var a;if((a=Object.create)&&_.Fe.test(a))a=a(null);else{a={};for(var b in a)a[b]=void 0}return a};_.Ie=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};_.Je=function(a,b){a=a||{};for(var c in a)_.Ie(a,c)&&(b[c]=a[c])};_.Ke=_.Ge(_.Ce,"gapi",{});_.Le=function(a,b,c){var d=new RegExp("([#].*&|[#])"+b+"=([^&#]*)","g");b=new RegExp("([?#].*&|[?#])"+b+"=([^&#]*)","g");if(a=a&&(d.exec(a)||b.exec(a)))try{c=decodeURIComponent(a[2])}catch(e){}return c};_.Me=new RegExp(/^/.source+/([a-zA-Z][-+.a-zA-Z0-9]*:)?/.source+/(\/\/[^\/?#]*)?/.source+/([^?#]*)?/.source+/(\?([^#]*))?/.source+/(#((#|[^#])*))?/.source+/$/.source);_.Ne=new RegExp(/(%([^0-9a-fA-F%]|[0-9a-fA-F]([^0-9a-fA-F%])?)?)*/.source+/%($|[^0-9a-fA-F]|[0-9a-fA-F]($|[^0-9a-fA-F]))/.source,"g");
_.Oe=new RegExp(/\/?\??#?/.source+"("+/[\/?#]/i.source+"|"+/[\uD800-\uDBFF]/i.source+"|"+/%[c-f][0-9a-f](%[89ab][0-9a-f]){0,2}(%[89ab]?)?/i.source+"|"+/%[0-9a-f]?/i.source+")$","i");_.Qe=function(a,b,c){_.Pe(a,b,c,"add","at")};_.Pe=function(a,b,c,d,e){if(a[d+"EventListener"])a[d+"EventListener"](b,c,!1);else if(a[e+"tachEvent"])a[e+"tachEvent"]("on"+b,c)};_.Re={};_.Re=_.Ge(_.Ce,"___jsl",_.He());_.Ge(_.Re,"I",0);_.Ge(_.Re,"hel",10);var Se,Te,Ue,Ve,Ye,We,Xe,Ze,$e;Se=function(a){var b=window.___jsl=window.___jsl||{};b[a]=b[a]||[];return b[a]};Te=function(a){var b=window.___jsl=window.___jsl||{};b.cfg=!a&&b.cfg||{};return b.cfg};Ue=function(a){return typeof a==="object"&&/\[native code\]/.test(a.push)};
Ve=function(a,b,c){if(b&&typeof b==="object")for(var d in b)!Object.prototype.hasOwnProperty.call(b,d)||c&&d==="___goc"&&typeof b[d]==="undefined"||(a[d]&&b[d]&&typeof a[d]==="object"&&typeof b[d]==="object"&&!Ue(a[d])&&!Ue(b[d])?Ve(a[d],b[d]):b[d]&&typeof b[d]==="object"?(a[d]=Ue(b[d])?[]:{},Ve(a[d],b[d])):a[d]=b[d])};
Ye=function(a,b){if(a&&!/^\s+$/.test(a)){for(;a.charCodeAt(a.length-1)==0;)a=a.substring(0,a.length-1);var c=a,d=Se("dm");d.push(20);try{var e=window.JSON.parse(a)}catch(h){}if(typeof e==="object")return d.push(21),e;try{e=window.JSON.parse("{"+a+"}")}catch(h){}if(typeof e==="object")return d.push(22),e;a=a.replace(RegExp("([^\"',{}\\s]+?)\\s*:\\s*(.*?)[,}\\s]","g"),function(h,k,l){l=l.startsWith('"')?"%DOUBLE_QUOTE%"+l.substring(1):l;l=l.endsWith('"')?l.slice(0,-1)+"%DOUBLE_QUOTE%":l;return"%DOUBLE_QUOTE%"+
k+"%DOUBLE_QUOTE%:"+l});a=a.replace(/\\'/g,"%SINGLE_QUOTE%");a=a.replace(/"/g,'\\"');a=a.replace(/'/g,'"');a=a.replace(/%SINGLE_QUOTE%/g,"'");a=a.replace(/%DOUBLE_QUOTE%/g,'"');try{e=window.JSON.parse(a)}catch(h){}if(typeof e==="object")return d.push(23),e;try{e=window.JSON.parse("{"+a+"}")}catch(h){}if(typeof e==="object")return d.push(24),e;a=document.getElementsByTagName("script")||[];var f;a.length>0&&(f=a[0].nonce||a[0].getAttribute("nonce"));if(f&&f===b||!f&&We())if(e=Xe(c),d.push(25),typeof e===
"object")return e;return{}}};We=function(){var a=window.location.hostname;return a?/(^|\.)(2mdn|ampproject|android|appspot|blogger|blogspot|chrome|chromium|doubleclick|gcpnode|ggpht|gmail|google|google-analytics|googleadservices|googleapis|googleapis-cn|googleoptimize|googlers|googlesource|googlesyndication|googletagmanager|googletagservices|googleusercontent|googlevideo|gstatic|tiltbrush|waze|withgoogle|youtube|ytimg)(\.com?|\.net|\.org)?(\.[a-z][a-z]|\.cat)?$/.test(a):!1};
Xe=function(a){try{var b=(new Function("return ("+a+"\n)"))()}catch(c){}if(typeof b==="object")return b;try{b=(new Function("return ({"+a+"\n})"))()}catch(c){}return b};Ze=function(a,b){var c={___goc:void 0};a.length&&a[a.length-1]&&Object.hasOwnProperty.call(a[a.length-1],"___goc")&&typeof a[a.length-1].___goc==="undefined"&&(c=a.pop());Ve(c,b);a.push(c)};
$e=function(a){Te(!0);var b=window.___gcfg,c=Se("cu"),d=window.___gu;b&&b!==d&&(Ze(c,b),window.___gu=b);b=Se("cu");var e=document.getElementsByTagName("script")||[];d=[];var f=[];f.push.apply(f,Se("us"));for(var h=0;h<e.length;++h)for(var k=e[h],l=0;l<f.length;++l)k.src&&k.src.indexOf(f[l])==0&&d.push(k);d.length==0&&e.length>0&&e[e.length-1].src&&d.push(e[e.length-1]);for(e=0;e<d.length;++e)d[e].getAttribute("gapi_processed")||(d[e].setAttribute("gapi_processed",!0),(f=d[e])?(h=f.nodeType,f=h==3||
h==4?f.nodeValue:f.textContent||""):f=void 0,h=d[e].nonce||d[e].getAttribute("nonce"),(f=Ye(f,h))&&b.push(f));a&&Ze(c,a);d=Se("cd");a=0;for(b=d.length;a<b;++a)Ve(Te(),d[a],!0);d=Se("ci");a=0;for(b=d.length;a<b;++a)Ve(Te(),d[a],!0);a=0;for(b=c.length;a<b;++a)Ve(Te(),c[a],!0)};_.af=function(a,b){var c=Te();if(!a)return c;a=a.split("/");for(var d=0,e=a.length;c&&typeof c==="object"&&d<e;++d)c=c[a[d]];return d===a.length&&c!==void 0?c:b};
_.bf=function(a,b){var c;if(typeof a==="string"){var d=c={};a=a.split("/");for(var e=0,f=a.length;e<f-1;++e){var h={};d=d[a[e]]=h}d[a[e]]=b}else c=a;$e(c)};var cf=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),_.Ge(_.Re,"ci",[]).push(a),window.__GOOGLEAPIS=void 0)};cf&&cf();$e();_.w("gapi.config.get",_.af);_.w("gapi.config.update",_.bf);
_.df=function(a){a=_.Be(a);return _.jc(a)};
var kf,lf,mf,nf,of,pf,qf,rf,sf,tf,uf,vf,wf,xf,zf,Af,Bf,Cf,Df,Ef,Ff,Gf,Hf,If,Jf,Kf,Lf,Mf,Nf,Of,Pf,Sf,Tf;mf=void 0;nf=function(a){try{return _.hb.JSON.parse.call(_.hb.JSON,a)}catch(b){return!1}};of=function(a){return Object.prototype.toString.call(a)};pf=of(0);qf=of(new Date(0));rf=of(!0);sf=of("");tf=of({});uf=of([]);
vf=function(a,b){if(b)for(var c=0,d=b.length;c<d;++c)if(a===b[c])throw new TypeError("Converting circular structure to JSON");d=typeof a;if(d!=="undefined"){c=Array.prototype.slice.call(b||[],0);c[c.length]=a;b=[];var e=of(a);if(a!=null&&typeof a.toJSON==="function"&&(Object.prototype.hasOwnProperty.call(a,"toJSON")||(e!==uf||a.constructor!==Array&&a.constructor!==Object)&&(e!==tf||a.constructor!==Array&&a.constructor!==Object)&&e!==sf&&e!==pf&&e!==rf&&e!==qf))return vf(a.toJSON.call(a),c);if(a==
null)b[b.length]="null";else if(e===pf)a=Number(a),isNaN(a)||isNaN(a-a)?a="null":a===-0&&1/a<0&&(a="-0"),b[b.length]=String(a);else if(e===rf)b[b.length]=String(!!Number(a));else{if(e===qf)return vf(a.toISOString.call(a),c);if(e===uf&&of(a.length)===pf){b[b.length]="[";var f=0;for(d=Number(a.length)>>0;f<d;++f)f&&(b[b.length]=","),b[b.length]=vf(a[f],c)||"null";b[b.length]="]"}else if(e==sf&&of(a.length)===pf){b[b.length]='"';f=0;for(c=Number(a.length)>>0;f<c;++f)d=String.prototype.charAt.call(a,
f),e=String.prototype.charCodeAt.call(a,f),b[b.length]=d==="\b"?"\\b":d==="\f"?"\\f":d==="\n"?"\\n":d==="\r"?"\\r":d==="\t"?"\\t":d==="\\"||d==='"'?"\\"+d:e<=31?"\\u"+(e+65536).toString(16).substr(1):e>=32&&e<=65535?d:"\ufffd";b[b.length]='"'}else if(d==="object"){b[b.length]="{";d=0;for(f in a)Object.prototype.hasOwnProperty.call(a,f)&&(e=vf(a[f],c),e!==void 0&&(d++&&(b[b.length]=","),b[b.length]=vf(f),b[b.length]=":",b[b.length]=e));b[b.length]="}"}else return}return b.join("")}};wf=/[\0-\x07\x0b\x0e-\x1f]/;
xf=/^([^"]*"([^\\"]|\\.)*")*[^"]*"([^"\\]|\\.)*[\0-\x1f]/;zf=/^([^"]*"([^\\"]|\\.)*")*[^"]*"([^"\\]|\\.)*\\[^\\\/"bfnrtu]/;Af=/^([^"]*"([^\\"]|\\.)*")*[^"]*"([^"\\]|\\.)*\\u([0-9a-fA-F]{0,3}[^0-9a-fA-F])/;Bf=/"([^\0-\x1f\\"]|\\[\\\/"bfnrt]|\\u[0-9a-fA-F]{4})*"/g;Cf=/-?(0|[1-9][0-9]*)(\.[0-9]+)?([eE][-+]?[0-9]+)?/g;Df=/[ \t\n\r]+/g;Ef=/[^"]:/;Ff=/""/g;Gf=/true|false|null/g;Hf=/00/;If=/[\{]([^0\}]|0[^:])/;Jf=/(^|\[)[,:]|[,:](\]|\}|[,:]|$)/;Kf=/[^\[,:][\[\{]/;Lf=/^(\{|\}|\[|\]|,|:|0)+/;Mf=/\u2028/g;
Nf=/\u2029/g;
Of=function(a){a=String(a);if(wf.test(a)||xf.test(a)||zf.test(a)||Af.test(a))return!1;var b=a.replace(Bf,'""');b=b.replace(Cf,"0");b=b.replace(Df,"");if(Ef.test(b))return!1;b=b.replace(Ff,"0");b=b.replace(Gf,"0");if(Hf.test(b)||If.test(b)||Jf.test(b)||Kf.test(b)||!b||(b=b.replace(Lf,"")))return!1;a=a.replace(Mf,"\\u2028").replace(Nf,"\\u2029");b=void 0;try{b=mf?[nf(a)]:eval("(function (var_args) {\n  return Array.prototype.slice.call(arguments, 0);\n})(\n"+a+"\n)")}catch(c){return!1}return b&&b.length===
1?b[0]:!1};Pf=function(){var a=((_.hb.document||{}).scripts||[]).length;if((kf===void 0||mf===void 0||lf!==a)&&lf!==-1){kf=mf=!1;lf=-1;try{try{mf=!!_.hb.JSON&&_.hb.JSON.stringify.call(_.hb.JSON,{a:[3,!0,new Date(0)],c:function(){}})==='{"a":[3,true,"1970-01-01T00:00:00.000Z"]}'&&nf("true")===!0&&nf('[{"a":3}]')[0].a===3}catch(b){}kf=mf&&!nf("[00]")&&!nf('"\u0007"')&&!nf('"\\0"')&&!nf('"\\v"')}finally{lf=a}}};_.Qf=function(a){if(lf===-1)return!1;Pf();return(kf?nf:Of)(a)};
_.Rf=function(a){if(lf!==-1)return Pf(),mf?_.hb.JSON.stringify.call(_.hb.JSON,a):vf(a)};Sf=!Date.prototype.toISOString||typeof Date.prototype.toISOString!=="function"||(new Date(0)).toISOString()!=="1970-01-01T00:00:00.000Z";
Tf=function(){var a=Date.prototype.getUTCFullYear.call(this);return[a<0?"-"+String(1E6-a).substr(1):a<=9999?String(1E4+a).substr(1):"+"+String(1E6+a).substr(1),"-",String(101+Date.prototype.getUTCMonth.call(this)).substr(1),"-",String(100+Date.prototype.getUTCDate.call(this)).substr(1),"T",String(100+Date.prototype.getUTCHours.call(this)).substr(1),":",String(100+Date.prototype.getUTCMinutes.call(this)).substr(1),":",String(100+Date.prototype.getUTCSeconds.call(this)).substr(1),".",String(1E3+Date.prototype.getUTCMilliseconds.call(this)).substr(1),
"Z"].join("")};Date.prototype.toISOString=Sf?Tf:Date.prototype.toISOString;
var Uf=function(){this.Gg=window.console};Uf.prototype.log=function(a){this.Gg&&this.Gg.log&&this.Gg.log(a)};Uf.prototype.error=function(a){this.Gg&&(this.Gg.error?this.Gg.error(a):this.Gg.log&&this.Gg.log(a))};Uf.prototype.warn=function(a){this.Gg&&(this.Gg.warn?this.Gg.warn(a):this.Gg.log&&this.Gg.log(a))};Uf.prototype.debug=function(){};_.Vf=new Uf;
_.Ig=function(a){if(!a)return"";if(/^about:(?:blank|srcdoc)$/.test(a))return window.origin||"";a.indexOf("blob:")===0&&(a=a.substring(5));a=a.split("#")[0].split("?")[0];a=a.toLowerCase();a.indexOf("//")==0&&(a=window.location.protocol+a);/^[\w\-]*:\/\//.test(a)||(a=window.location.href);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");c!=-1&&(b=b.substring(0,c));c=a.substring(0,a.indexOf("://"));if(!c)throw Error("s`"+a);if(c!=="http"&&c!=="https"&&c!=="chrome-extension"&&c!=="moz-extension"&&
c!=="file"&&c!=="android-app"&&c!=="chrome-search"&&c!=="chrome-untrusted"&&c!=="chrome"&&c!=="app"&&c!=="devtools")throw Error("t`"+c);a="";var d=b.indexOf(":");if(d!=-1){var e=b.substring(d+1);b=b.substring(0,d);if(c==="http"&&e!=="80"||c==="https"&&e!=="443")a=":"+e}return c+"://"+b+a};
_.bi=function(a){var b=window.___jsl=window.___jsl||{};b.cfg=!a&&b.cfg||{};return b.cfg};_.ci=function(a){var b=_.bi();if(!a)return b;a=a.split("/");for(var c=0,d=a.length;b&&typeof b==="object"&&c<d;++c)b=b[a[c]];return c===a.length&&b!==void 0?b:void 0};
var Vk=function(){this.Wx={f3:Ok?"../"+Ok:null,Mz:Pk,NX:Qk,gza:Rk,Bo:Sk,Xza:Tk};this.Wf=_.Ce;this.m2=this.jea;this.afa=/MSIE\s*[0-8](\D|$)/.test(window.navigator.userAgent);if(this.Wx.f3){this.Wf=this.Wx.NX(this.Wf,this.Wx.f3);var a=this.Wf.document,b=a.createElement("script");b.setAttribute("type","text/javascript");b.text="window.doPostMsg=function(w,s,o) {window.setTimeout(function(){w.postMessage(s,o);},0);};";a.body.appendChild(b);this.m2=this.Wf.doPostMsg}this.hQ={};this.JQ={};a=(0,_.Eb)(this.FK,
this);_.Qe(this.Wf,"message",a);_.Ge(_.Re,"RPMQ",[]).push(a);this.Wf!=this.Wf.parent&&Uk(this,this.Wf.parent,this.cM(this.Wf.name),"*")};Vk.prototype.cM=function(a){return'{"h":"'+escape(a)+'"}'};var Wk=function(a){var b=null;a.indexOf('{"h":"')===0&&a.indexOf('"}')===a.length-2&&(b=unescape(a.substring(6,a.length-2)));return b},Xk=function(a){if(!/^\s*{/.test(a))return!1;a=_.Qf(a);return a!==null&&typeof a==="object"&&!!a.g};
Vk.prototype.FK=function(a){var b=String(a.data);_.Vf.debug("gapix.rpc.receive("+Rk+"): "+(!b||b.length<=512?b:b.substr(0,512)+"... ("+b.length+" bytes)"));var c=b.indexOf("!_")!==0;c||(b=b.substring(2));var d=Xk(b);if(!c&&!d){if(!d&&(c=Wk(b))){if(this.hQ[c])this.hQ[c]();else this.JQ[c]=1;return}var e=a.origin,f=this.Wx.Mz;this.afa?_.Ce.setTimeout(function(){f(b,e)},0):f(b,e)}};Vk.prototype.Hb=function(a,b){a===".."||this.JQ[a]?(b(),delete this.JQ[a]):this.hQ[a]=b};
var Uk=function(a,b,c,d){var e=Xk(c)?"":"!_";_.Vf.debug("gapix.rpc.send("+Rk+"): "+(!c||c.length<=512?c:c.substr(0,512)+"... ("+c.length+" bytes)"));a.m2(b,e+c,d)};Vk.prototype.jea=function(a,b,c){a.postMessage(b,c)};Vk.prototype.send=function(a,b,c){(a=this.Wx.NX(this.Wf,a))&&!a.closed&&Uk(this,a,b,c)};var Yk,Zk,$k,al,bl,cl,dl,Ok,Rk,el,fl,gl,Qk,Sk,il,jl,ol,pl,rl,Tk,tl,sl,kl,ll,ul,Pk,vl,wl;Yk=0;Zk=[];$k={};al={};bl=_.Ce.location.href;cl=_.Le(bl,"rpctoken");dl=_.Le(bl,"parent")||_.De.referrer;Ok=_.Le(bl,"rly");Rk=Ok||(_.Ce!==_.Ce.top||_.Ce.opener)&&_.Ce.name||"..";el=null;fl={};gl=function(){};_.hl={send:gl,Hb:gl,cM:gl};
Qk=function(a,b){var c=a;b.charAt(0)=="/"&&(b=b.substring(1),c=_.Ce.top);if(b.length===0)return c;for(b=b.split("/");b.length;){a=b.shift();a.charAt(0)=="{"&&a.charAt(a.length-1)=="}"&&(a=a.substring(1,a.length-1));var d=a;if(d==="..")c=c==c.parent?c.opener:c.parent;else if(d!==".."&&c.frames[d]){var e=c;a=d;c=c.frames[d];if(!("postMessage"in c))if(c instanceof HTMLIFrameElement&&"contentWindow"in c)c=c.contentWindow!=null&&"postMessage"in c.contentWindow?c.contentWindow:null;else{d=null;e=_.Ga(e.document.getElementsByTagName("iframe"));
for(var f=e.next();!f.done;f=e.next())if(f=f.value,f.getAttribute("id")==a||f.getAttribute("name")==a)d=f;if(d&&"contentWindow"in d)c=d.contentWindow!=null?d.contentWindow:null;else throw Error("F`"+c+"`"+a);}}else return null}return c};Sk=function(a){return(a=$k[a])&&a.token};il=function(a){if(a.f in{})return!1;var b=a.t,c=$k[a.r];a=a.origin;return c&&(c.token===b||!c.token&&!b)&&(a===c.origin||c.origin==="*")};
jl=function(a){var b=a.id.split("/"),c=b[b.length-1],d=a.origin;return function(e){var f=e.origin;return e.f==c&&(d==f||d=="*")}};_.ml=function(a,b,c){a=kl(a);al[a.name]={Uh:b,kw:a.kw,vt:c||il};ll()};_.nl=function(a){a=kl(a);delete al[a.name]};ol={};pl=function(a,b){(a=ol["_"+a])&&a[1](this)&&a[0].call(this,b)};rl=function(a){var b=a.c;if(!b)return gl;var c=a.r,d=a.g?"legacy__":"";return function(){var e=[].slice.call(arguments,0);e.unshift(c,d+"__cb",null,b);_.ql.apply(null,e)}};
Tk=function(a){el=a};tl=function(a){fl[a]||(fl[a]=_.Ce.setTimeout(function(){fl[a]=!1;sl(a)},0))};sl=function(a){var b=$k[a];if(b&&b.ready){var c=b.oN;for(b.oN=[];c.length;)_.hl.send(a,_.Rf(c.shift()),b.origin)}};kl=function(a){return a.indexOf("legacy__")===0?{name:a.substring(8),kw:!0}:{name:a,kw:!1}};
ll=function(){for(var a=_.ci("rpc/residenceSec")||60,b=(new Date).getTime()/1E3,c,d=0;c=Zk[d];++d){var e=c.Ep;if(!e||a>0&&b-c.timestamp>a)Zk.splice(d,1),--d;else{var f=e.s,h=al[f]||al["*"];if(h)if(Zk.splice(d,1),--d,e.origin=c.origin,c=rl(e),e.callback=c,h.vt(e)){if(f!=="__cb"&&!!h.kw!=!!e.g)break;e=h.Uh.apply(e,e.a);e!==void 0&&c(e)}else _.Vf.debug("gapix.rpc.rejected("+Rk+"): "+f)}}};ul=function(a,b,c){Zk.push({Ep:a,origin:b,timestamp:(new Date).getTime()/1E3});c||ll()};
Pk=function(a,b){a=_.Qf(a);ul(a,b,!1)};vl=function(a){for(;a.length;)ul(a.shift(),this.origin,!0);ll()};wl=function(a){var b=!1;a=a.split("|");var c=a[0];c.indexOf("/")>=0&&(b=!0);return{id:c,origin:a[1]||"*",AL:b}};
_.xl=function(a,b,c,d){var e=wl(a);d&&(_.Ce.frames[e.id]=_.Ce.frames[e.id]||d);a=e.id;if(!$k.hasOwnProperty(a)){c=c||null;d=e.origin;if(a==="..")d=_.Ig(dl),c=c||cl;else if(!e.AL){var f=_.De.getElementById(a);f&&(f=f.src,d=_.Ig(f),c=c||_.Le(f,"rpctoken"))}e.origin==="*"&&d||(d=e.origin);$k[a]={token:c,oN:[],origin:d,ema:b,W2:function(){var h=a;$k[h].ready=1;sl(h)}};_.hl.Hb(a,$k[a].W2)}return $k[a].W2};
_.ql=function(a,b,c,d){a=a||"..";_.xl(a);a=a.split("|",1)[0];var e=b,f=a,h=[].slice.call(arguments,3),k=c,l=Rk,m=cl,n=$k[f],p=l,q=wl(f);if(n&&f!==".."){if(q.AL){if(!(m=$k[f].ema)){m=el?el.substring(1).split("/"):[Rk];p=m.length-1;for(f=_.Ce.parent;f!==_.Ce.top;){var r=f.parent;if(!p--){for(var v=null,t=r.frames.length,y=0;y<t;++y)r.frames[y]==f&&(v=y);m.unshift("{"+v+"}")}f=r}m="/"+m.join("/")}p=m}else p=l="..";m=n.token}k&&q?(n=il,q.AL&&(n=jl(q)),ol["_"+ ++Yk]=[k,n],k=Yk):k=null;h={s:e,f:l,r:p,t:m,
c:k,a:h};e=kl(e);h.s=e.name;h.g=e.kw;$k[a].oN.push(h);tl(a)};if(typeof _.Ce.postMessage==="function"||typeof _.Ce.postMessage==="object")_.hl=new Vk,_.ml("__cb",pl,function(){return!0}),_.ml("_processBatch",vl,function(){return!0}),_.xl("..");
_.w("gapi.rpc.setup",_.xl);_.w("gapi.rpc.register",_.ml);_.w("gapi.rpc.call",_.ql);_.w("gapi.rpc.unregister",_.nl);_.w("gapi.rpc.sendHandshake",function(a,b){_.xl(a)();_.hl.send(a,_.hl.cM(b),"*")});
});
// Google Inc.
